version: '3.8'

services:
  paimonbot:
    build: .
    container_name: paimonbot
    restart: always
    env_file:
      - .env
    volumes:
      - ./database.json:/app/database.json
      - ./config.json:/app/config.json
