version: '3.8'

services:
  paimonbot:
    build: .
    container_name: paimonbot
    restart: always
    env_file:
      - .env
    volumes:
      - ./paimon.db:/app/paimon.db
      - ./backups:/app/backups
      - ./config.json:/app/config.json
